version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
    groups:
      qwik:
        patterns:
          - 'qwik*'
      lint:
        patterns:
          - 'lint*'
          - 'prettier'
      css:
        patterns:
          - '*css*'
          - 'autoprefixer'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
