version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 15
    groups:
      qwik:
        patterns:
        - "*qwik*"
      lint:
        patterns:
        - "*lint*"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
